### PR TITLE
Update ReadTime.php

### PR DESCRIPTION
**Pull request by marad3r**
PhpStan and PhpStorm couldn't resolve return types

### CODE REVIEW

**Comment by peter279k** [comment]
Could you have the `phpstan` command to reproduce this issue you mention?

**Comment by marad3r** [comment]
But also phpStorm can't resolve it if you try to click on this declaration

**Comment by peter279k** [comment]
I don't use PHPStorm as my coding editor and I will try to run `phpstan` command on my local dev environment :).

**Comment by peter279k** [comment]
Ok. I've got error via `vendor/bin/phpstan analyse --level=2 src` command:

```
------ ---------------------------------------------------------------------------------------
  Line   ReadTime.php
 ------ ---------------------------------------------------------------------------------------
  99     Return typehint of method Mtownsend\ReadTime\ReadTime::abbreviated() has invalid type
         Mtownsend\ReadTime\Mtownsend\ReadTime\ReadTime.
  244    PHPDoc tag @param has invalid value (bool): Unexpected token "\n     *", expected
         variable at offset 68
  244    Return typehint of method Mtownsend\ReadTime\ReadTime::ltr() has invalid type
         Mtownsend\ReadTime\Mtownsend\ReadTime\ReadTime.
  256    Return typehint of method Mtownsend\ReadTime\ReadTime::omitSeconds() has invalid type
         Mtownsend\ReadTime\Mtownsend\ReadTime\ReadTime.
  306    Return typehint of method Mtownsend\ReadTime\ReadTime::rtl() has invalid type
         Mtownsend\ReadTime\Mtownsend\ReadTime\ReadTime.
  318    Return typehint of method Mtownsend\ReadTime\ReadTime::setTranslation() has invalid
         type Mtownsend\ReadTime\Mtownsend\ReadTime\ReadTime.
  336    Return typehint of method Mtownsend\ReadTime\ReadTime::timeOnly() has invalid type
         Mtownsend\ReadTime\Mtownsend\ReadTime\ReadTime.
  377    Return typehint of method Mtownsend\ReadTime\ReadTime::wpm() has invalid type
         Mtownsend\ReadTime\Mtownsend\ReadTime\ReadTime.
 ------ ---------------------------------------------------------------------------------------
```

After running above command on this PR, the error is as follows:

```
 ------ -----------------------------------------------------------------------------------
  Line   ReadTime.php
 ------ -----------------------------------------------------------------------------------
  244    PHPDoc tag @param has invalid value (bool): Unexpected token "\n     *", expected
         variable at offset 68
  306    Return typehint of method Mtownsend\ReadTime\ReadTime::rtl() has invalid type
         Mtownsend\ReadTime\Mtownsend\ReadTime\ReadTime.
 ------ -----------------------------------------------------------------------------------
```

**Comment by marad3r** [comment]
Sorry, I'm on holiday! I haven't other errors. Anyway I think it will be better to type the right namespaces in phpDoc.

**Comment by peter279k** [comment]
> Sorry, I'm on holiday! I haven't other errors. Anyway I think it will be better to type the right namespaces in phpDoc.

Never mind. I think this will be another PR to concern about these issues I mention.

Thanks :).

**Review by peter279k — APPROVED** [review]

**Comment by marad3r** [comment]
Hi! Are you going to merge this PR?

**Comment by peter279k** [comment]
PIN @mtownsend5512.

**Pull request merged**
